package berlin.tu.cyclinginfrastructurebackend.service.dto.api;

import berlin.tu.cyclinginfrastructurebackend.domain.SegmentEvent;

import java.util.UUID;

public record SegmentEventDto(
        UUID id,
        Long segmentId,
        UUID rideId,
        String eventType,
        Long eventTimestamp,
        String dayOfWeek,
        Integer hourOfDay,
        String rideIntent,
        String bikeType,
        Double pathBearingDegrees,
        String highway,
        String surface,
        String smoothness,
        String lit,
        String cyclewayType,
        String cyclewayLocation,
        String cyclewaySurface,
        Double cyclewayWidth,
        Boolean bicycleOneway,
        boolean weatherEnriched,
        Double temperature2m,
        Double precipitation,
        Double windSpeed10m,
        Double windDirection10m,
        Integer weatherCode,
        Double relativeWindAngleDegrees,
        String windExposure,
        boolean ohsomeEnriched,
        boolean trafficEnriched,
        String trafficEnrichmentStatus,
        String trafficCondition,
        String trafficSourceType,
        Integer trafficVolumeKfz,
        Double trafficSpeedKfz,
        Integer trafficVolumePkw,
        Double trafficSpeedPkw,
        Integer trafficVolumeLkw,
        Double trafficSpeedLkw
) {

    public static SegmentEventDto from(SegmentEvent event) {
        return new SegmentEventDto(
                event.getId(),
                event.getSegment().getId(),
                event.getRide() != null ? event.getRide().getId() : null,
                event.getEventType().name(),
                event.getEventTimestamp(),
                event.getDayOfWeek() != null ? event.getDayOfWeek().name() : null,
                event.getHourOfDay(),
                event.getRideIntent() != null ? event.getRideIntent().name() : null,
                event.getRide() != null && event.getRide().getBikeType() != null ? event.getRide().getBikeType().name() : null,
                event.getPathBearingDegrees(),
                event.getHighway(),
                event.getSurface(),
                event.getSmoothness(),
                event.getLit(),
                event.getCyclewayType() != null ? event.getCyclewayType().name() : null,
                event.getCyclewayLocation() != null ? event.getCyclewayLocation().name() : null,
                event.getCyclewaySurface(),
                event.getCyclewayWidth(),
                event.getBicycleOneway(),
                event.isWeatherEnriched(),
                event.getTemperature2m(),
                event.getPrecipitation(),
                event.getWindSpeed10m(),
                event.getWindDirection10m(),
                event.getWeatherCode(),
                event.getRelativeWindAngleDegrees(),
                event.getWindExposure() != null ? event.getWindExposure().name() : null,
                event.isOhsomeEnriched(),
                event.isTrafficEnriched(),
                event.getTrafficEnrichmentStatus() != null ? event.getTrafficEnrichmentStatus().name() : null,
                event.getTrafficCondition() != null ? event.getTrafficCondition().name() : null,
                event.getTrafficSourceType() != null ? event.getTrafficSourceType().name() : null,
                event.getTrafficVolumeKfz(),
                event.getTrafficSpeedKfz(),
                event.getTrafficVolumePkw(),
                event.getTrafficSpeedPkw(),
                event.getTrafficVolumeLkw(),
                event.getTrafficSpeedLkw()
        );
    }
}
